redis:
  build: ./env/redis
  ports:
    - "6379:6379"
  volumes:
    - ./redis:/data
    - ./log/redis:/var/log/redis

mysql:
  build: ./env/mysql
  ports:
    - "3306:3306"
  volumes:
    - ./database:/var/lib/mysql
    - ./log/mysql:/var/log/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456

php-fpm:
  build: ./env/php-fpm
  ports:
    - "9000:9000"
  links:
    - "redis"
    - "mysql"
  volumes:
    - ./app:/var/www/html

nginx:
  build: ./env/nginx
  ports:
    - "80:80"
  links:
    - "php-fpm"
  volumes:
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx
